# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Optional&lt;Void&gt;
tagline:             It's idiocy
url:                 http://eriklarko.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Erik Larkö
  email:             erik@larko.se

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/eriklarko/eriklarko.github.io
